Descarga (1,0 puntos): Con el fin de reducir los tiempos de todo el proceso, se debe generar un archivo para almacenamiento de la información de manera local. De esta forma, si el archivo se encuentra disponible localmente, no realice la extracción web sino que parta de un archivo de texto plano. Si su proyecto no tenía archivos para descarga, este paso se cumple generando un archivo de texto plano en #el formato que desee para contener la información extraída.

In [14]:
from bs4 import BeautifulSoup
import requests
import urllib2

baloto = "http://www.baloto.com/filtro-historico-de-resultados.php"
res = requests.get('http://www.baloto.com/filtro-historico-de-resultados.php')
page = urllib2.urlopen(baloto)
soup = BeautifulSoup(page)
print soup.prettify()
soup.find_all('a')
gh = bs4.BeautifulSoup(res.text, "lxml")
tabla_archivos = gh.find_all('td', {'class':'field-items'})

for content in tabla_archivos:
    lineas_a = style('a')
    if lineas_a:
        texto = "Se encontro el archivo '{}'".format(lineas_a[0].string.encode("utf-8"))
        texto += " con enlace '{}'.".format(lineas_a[0].get("href"))
        print(texto)

tabla_archivos = gh.find_all('td')
tabla_archivos = gh.find_all('td', {'class':'style'})

<!DOCTYPE html>
<html dir="ltr" version="XHTML+RDFa 1.0" xml:lang="es" xmlns="http://www.w3.org/1999/xhtml" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:og="http://ogp.me/ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:sioc="http://rdfs.org/sioc/ns#" xmlns:sioct="http://rdfs.org/sioc/types#" xmlns:skos="http://www.w3.org/2004/02/skos/core#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#">
 <head profile="http://www.w3.org/1999/xhtml/vocab">
  <meta content="width=1350" name="viewport"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <link href="sites/default/files/favicon-baloto_3.png" rel="shortcut icon" type="image/png"/>
  <meta content="Drupal 7 (http://drupal.org)" name="Generator"/>
  <title>
   Historico de Resultados | Baloto
  </title>
  <link href="sites/default/files/css/css_Z_KQyXTcIGmFPRfGZOOTJ1xsEckXlqMhF53CkTgnOVA.css" media="all" rel="stylesheet" type="text/css"/>
  <link href="sites/default/files/css/css_hR-iZ_yz_txFBJ9GrjlvsKYDqZzImBb2HpX-zvLFeyY.css" media="all" rel="stylesheet" type="text/css"/>
  <link href="sites/default/files/css/css_SYYjRhLCZ5fsrYqzw2JQrxGY4OArqHCSaaKHZ3QUSEU.css" media="all" rel="stylesheet" type="text/css"/>
  <link href="sites/default/files/css/css_6UAlVYYRtTQdprT2v9Yrb9llyFOBJZTP9caLzTNzXKQ.css" media="all" rel="stylesheet" type="text/css"/>
  <script src="sites/default/files/js/js_3jHghlMLrjr9xXAC0JufqSSch3oAbkZstSqYdc4uuck.js" type="text/javascript">
  </script>
  <script src="sites/default/files/js/js_4RLg_0mcLz8_00RMt9A9Ud5xsS4fiSi3ArVfSZMKjy4.js" type="text/javascript">
  </script>
  <script src="sites/default/files/js/js_R9UbiVw2xuTUI0GZoaqMDOdX0lrZtgX-ono8RVOUEVc.js" type="text/javascript">
  </script>
  <script src="sites/default/files/js/js_towk5-DuSmR6qpxOf9IR0xe57c9MmXcMSfWH12irOoM.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   <!--//--><![CDATA[//><!--
var _gaq = _gaq || [];_gaq.push(["_setAccount", "UA-33502596-1"]);_gaq.push(["_trackPageview"]);(function() {var ga = document.createElement("script");ga.type = "text/javascript";ga.async = true;ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";var s = document.getElementsByTagName("script")[0];s.parentNode.insertBefore(ga, s);})();
//--><!]]>
  </script>
  <script src="sites/default/files/js/js_RGp-0hf11GD0QrH_fydMXMcSyZrMtGE6nZBCLnUDvHA.js" type="text/javascript">
  </script>
  <script src="sites/default/files/js/js_PCPOMvpnBM67b24D4JCbFqlOnrSzD6T1tjJ6e7Dv-S4.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   <!--//--><![CDATA[//><!--
jQuery.extend(Drupal.settings, {"basePath":"\/","pathPrefix":"","ajaxPageState":{"theme":"baloto","theme_token":"pX8yIaj2DvZi62NXwqU9p8abWC9vXvoW66iVxHwGP1M","js":{"misc\/jquery.js":1,"misc\/jquery.once.js":1,"misc\/drupal.js":1,"misc\/jquery.cookie.js":1,"misc\/jquery.form.js":1,"misc\/ajax.js":1,"sites\/all\/modules\/contrib\/admin_menu\/admin_devel\/admin_devel.js":1,"public:\/\/languages\/es_u-0PgVze9vCngA75HNb_6hkx2rlwTru3UuPLbkXDMmM.js":1,"sites\/all\/libraries\/colorbox\/colorbox\/jquery.colorbox-min.js":1,"sites\/all\/modules\/contrib\/colorbox\/js\/colorbox.js":1,"sites\/all\/modules\/contrib\/colorbox\/styles\/default\/colorbox_default_style.js":1,"sites\/all\/modules\/contrib\/colorbox\/js\/colorbox_load.js":1,"sites\/all\/modules\/contrib\/colorbox\/js\/colorbox_inline.js":1,"sites\/all\/modules\/contrib\/views_slideshow\/js\/views_slideshow.js":1,"sites\/all\/modules\/contrib\/ctools\/js\/auto-submit.js":1,"sites\/all\/modules\/contrib\/views\/js\/base.js":1,"misc\/progress.js":1,"sites\/all\/modules\/contrib\/views\/js\/ajax_view.js":1,"sites\/all\/modules\/contrib\/google_analytics\/googleanalytics.js":1,"sites\/all\/modules\/custom\/baloto_tabs_navegacion\/js\/baloto_tabs_navegacion.js":1,"0":1,"sites\/all\/modules\/custom\/baloto_acumulado\/js\/menu_superior.js":1,"sites\/all\/modules\/custom\/baloto_acumulado\/js\/jquery.cookie.js":1,"sites\/all\/themes\/baloto\/js\/script.js":1,"sites\/all\/themes\/baloto\/js\/customSelect.jquery.js":1},"css":{"modules\/system\/system.base.css":1,"modules\/system\/system.menus.css":1,"modules\/system\/system.messages.css":1,"modules\/system\/system.theme.css":1,"sites\/all\/modules\/contrib\/date\/date_api\/date.css":1,"modules\/field\/theme\/field.css":1,"modules\/node\/node.css":1,"modules\/search\/search.css":1,"modules\/user\/user.css":1,"sites\/all\/modules\/contrib\/views\/css\/views.css":1,"sites\/all\/modules\/contrib\/colorbox\/styles\/default\/colorbox_default_style.css":1,"sites\/all\/modules\/contrib\/ctools\/css\/ctools.css":1,"sites\/all\/modules\/contrib\/views_slideshow\/views_slideshow.css":1,"sites\/all\/modules\/custom\/baloto_acumulado\/css\/menu_superior.css":1,"sites\/all\/modules\/custom\/baloto_tabs_navegacion\/css\/baloto_tabs_navegacion.css":1,"sites\/all\/themes\/baloto\/css\/style.css":1,"sites\/all\/themes\/baloto\/fuentes\/tablero\/MyFontsWebfontsKit.css":1,"sites\/all\/themes\/baloto\/fuentes\/astri\/stylesheet.css":1}},"colorbox":{"opacity":"0.85","current":"{current} of {total}","previous":"\u00ab Prev","next":"Next \u00bb","close":"Cerrar","maxWidth":"100%","maxHeight":"100%","fixed":true,"__drupal_alter_by_ref":["default"]},"views":{"ajax_path":"administrator\/index.php\/ajax\/results","ajaxViews":{"views_dom_id:7dc0d5dbacdd2df4860a568bbe74e579":{"view_name":"historico_de_resultados","view_display_id":"page","view_args":"","view_path":"filtro-historico-de-resultados","view_base_path":"filtro-historico-de-resultados","view_dom_id":"7dc0d5dbacdd2df4860a568bbe74e579","pager_element":0}}},"googleanalytics":{"trackOutbound":1,"trackMailto":1,"trackDownload":1,"trackDownloadExtensions":"7z|aac|arc|arj|asf|asx|avi|bin|csv|doc|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls|xml|z|zip"}});
//--><!]]>
  </script>
 </head>
 <body class="html not-front not-logged-in no-sidebars page-filtro-historico-de-resultados">
  <div id="skip-link">
   <a class="element-invisible element-focusable" href="#main-content">
    Pasar al contenido principal
   </a>
  </div>
  <div id="cargainicio">
  </div>
  <div id="page-wrapper">
   <!--
  Espacio para la seccion "tus sueños"
  <div id="header">
    </div>
  -->
   <div id="top">
    <div class="t-content">
     <div id="t-logo">
      <a class="left-logo" href="index.php" title="Inicio">
       <img alt="Inicio" src="http://bb6e4750a9fd4af12e39-0b5832f7432214ede1c05fe6bed4dbf9.r61.cf2.rackcdn.com/sites/all/themes/baloto/images/small-logo.png"/>
      </a>
      <div class="social">
       <p class="social-text hide-text">
        SÍGUENOS EN NUESTROS CANALES OFICIALES:
       </p>
       <a class="link-fb hide-text" href="http://bit.ly/facebook-baloto" target="_blank" title="">
        facebook
       </a>
       <span class="separator">
       </span>
       <a class="link-tw hide-text" href="http://bit.ly/twitter-baloto" target="_blank" title="">
        twitter
       </a>
      </div>
     </div>
    </div>
   </div>
   <div id="page-bkg-normal">
   </div>
   <div id="page-bkg-revancha">
   </div>
   <div id="page-bkg-dobles">
   </div>
   <div id="content-wrapper">
    <div id="texture-content-wrapper">
     <div id="pre-content">
      <div class="region region-precontent">
       <div class="block block-menu" id="block-menu-menu-menu-principal">
        <div class="content">
         <ul class="menu">
          <li class="first last leaf">
           <a href="index.php" title="">
            MENÚ
           </a>
          </li>
         </ul>
        </div>
       </div>
       <div class="block block-baloto-acumulado" id="block-baloto-acumulado-menu-superior-quicktabs">
        <div class="content">
         <a class="prev-tab btn-tab" href="#">
         </a>
         <ul id="tabs-navegacion-h">
          <li class="tab-navegacion-h first-tab">
           <span>
            ¿Qué es Baloto Revancha?
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            ¿Cómo jugar?
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            Resultados
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            Balotímetro
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            Estadística de números
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            ¿Cómo ganar y cobrar?
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            ¿Dónde Jugar?
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            GTECH
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            Beneficios para Colombia
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            Contáctenos
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            Términos y condiciones
           </span>
          </li>
          <li class="tab-navegacion-h">
           <span>
            Comunicados Oficiales
           </span>
          </li>
          <li class="tab-navegacion-h last-tab">
           <span>
            Vídeos
           </span>
          </li>
         </ul>
         <a class="next-tab active btn-tab" href="#">
         </a>
        </div>
       </div>
       <div class="block block-block" id="block-block-1">
        <div class="content">
         <p>
          <img alt="" src="/administrator/images/Banner_Balotomania3.jpg"/>
         </p>
        </div>
       </div>
      </div>
     </div>
     <div id="content">
      <div class="tabs">
      </div>
      <div class="region region-content">
       <div class="block block-system" id="block-system-main">
        <div class="content">
         <div class="view view-historico-de-resultados view-id-historico_de_resultados view-display-id-page view-dom-id-7dc0d5dbacdd2df4860a568bbe74e579">
          <div class="view-filters">
           <form accept-charset="UTF-8" action="/filtro-historico-de-resultados" class="ctools-auto-submit-full-form" id="views-exposed-form-historico-de-resultados-page" method="get">
            <div>
             <div class="views-exposed-form">
              <div class="views-exposed-widgets clearfix">
               <div class="views-exposed-widget views-widget-filter-field_a_o_value" id="edit-field-a-o-value-wrapper">
                <label for="edit-field-a-o-value">
                 Año
                </label>
                <div class="views-widget">
                 <div class="form-item form-type-select form-item-field-a-o-value">
                  <select class="form-select required" id="edit-field-a-o-value" name="field_a_o_value">
                   <option selected="selected" value="2016">
                    2016
                   </option>
                   <option value="2015">
                    2015
                   </option>
                   <option value="2014">
                    2014
                   </option>
                   <option value="2013">
                    2013
                   </option>
                   <option value="2012">
                    2012
                   </option>
                   <option value="2011">
                    2011
                   </option>
                   <option value="2010">
                    2010
                   </option>
                   <option value="2009">
                    2009
                   </option>
                   <option value="2008">
                    2008
                   </option>
                   <option value="2007">
                    2007
                   </option>
                   <option value="2006">
                    2006
                   </option>
                   <option value="2005">
                    2005
                   </option>
                   <option value="2004">
                    2004
                   </option>
                   <option value="2003">
                    2003
                   </option>
                   <option value="2002">
                    2002
                   </option>
                   <option value="2001">
                    2001
                   </option>
                  </select>
                 </div>
                </div>
               </div>
               <div class="views-exposed-widget views-submit-button">
                <input class="ctools-use-ajax ctools-auto-submit-click js-hide form-submit" id="edit-submit-historico-de-resultados" name="" type="submit" value="Aplicar"/>
               </div>
              </div>
             </div>
            </div>
           </form>
          </div>
          <div class="view-content">
           <div class="views-row views-row-1 views-row-odd views-row-first views-row-last">
            <div class="ds-1col node node-historico-de-resultados view-mode-full clearfix ">
             <div class="field field-name-historico field-type-ds field-label-hidden">
              <div class="field-items">
               <div class="field-item even">
                Histórico
               </div>
              </div>
             </div>
             <div class="field field-name-title field-type-ds field-label-hidden">
              <div class="field-items">
               <div class="field-item even" property="dc:title">
                <h2>
                 2016
                </h2>
               </div>
              </div>
             </div>
             <div class="field field-name-body field-type-text-with-summary field-label-hidden">
              <div class="field-items">
               <div class="field-item even" property="content:encoded">
                <p>
                </p>
                <table align="center" border="0" cellpadding="0" cellspacing="6" style="width: 740px;">
                 <tbody>
                  <tr>
                   <td colspan="3" rowspan="1" style="text-align: center;">
                    <h2 style="font-size: 13px; background-color: #1E7EC6; line-height: 20px;">
                     <a href="index.php#node?qt-navegacion_internas_baloto=2#qt-navegacion_internas_baloto" style="font-size: 13px; font-weight: normal;">
                      <img alt="" class="media-image" height="66" src="sites/default/files/logoBAL_0.gif" style="font-size: 13px;" typeof="foaf:Image" width="154"/>
                     </a>
                    </h2>
                    <p style="font-size: 13px; background-color: #1E7EC6; line-height: 20px;">
                     <span style="font-size:16px;">
                      <span style="font-family:arial,helvetica,sans-serif;">
                       <strong>
                        Nuevo acumulado:
                        <br/>
                        $10.500'000.000
                       </strong>
                      </span>
                     </span>
                    </p>
                   </td>
                   <td colspan="3" rowspan="1" style="text-align: center;">
                    <p style="font-size: 13px; background-color: #1E7EC6; line-height: 20px;">
                     <img alt="" class="media-image" height="66" src="sites/default/files/logoREV_0.gif" style="font-size: 13px;" typeof="foaf:Image" width="154"/>
                     <br/>
                     <span style="font-size:16px;">
                      <span style="font-family:arial,helvetica,sans-serif;">
                       <strong>
                        Nuevo acumulado:
                        <br/>
                        $10.200'000.000
                       </strong>
                      </span>
                     </span>
                    </p>
                   </td>
                  </tr>
                  <tr>
                   <td colspan="6" style="text-align: center;">
                    <p>
                     <span style="font-size:12px;">
                      <span style="font-family:arial,helvetica,sans-serif;">
                       <span style="line-height: 20px;">
                        Juegan el miércoles 19
                       </span>
                      </span>
                      <span style="font-family:arial,helvetica,sans-serif;">
                       <span style="line-height: 20px; ">
                        de octubre de 2016
                       </span>
                      </span>
                     </span>
                    </p>
                   </td>
                  </tr>
                  <tr>
                   <td colspan="6" style="text-align: right;">
                    <strong>
                     Octubre
                    </strong>
                   </td>
                  </tr>
                  <tr>
                   <td style="text-align: center;">
                    1617
                   </td>
                   <td style="text-align: center;">
                    01 - 05 - 12 - 22 - 33 - 40
                   </td>
                   <td style="text-align: left;width:50px;">
                   </td>
                   <td style="text-align: right;width:50px;">
                   </td>
                   <td style="text-align: center;">
                    03 - 05 - 15 - 17 - 33 - 42
                   </td>
                   <td style="text-align: center;">
                    15/10/16
                   </td>
                  </tr>
                  <tr>
                   <td style="text-align: center;">
                    1616
                   </td>
                   <td style="text-align: center;">
                    03 - 06 - 14 - 36 - 39 - 43
                   </td>
                   <td style="text-align: left;width:50px;">
                   </td>
                   <td style="text-align: right;width:50px;">
                   </td>
                   <td style="text-align: center;">
                    15 - 18 - 22 - 33 - 42 - 45
                   </td>
                   <td style="text-align: center;">
                    12/10/16
                   </td>
                  </tr>
                  <tr>
                   <td style="text-align: center;">
                    1615
                   </td>
                   <td style="text-align: center;">
                    01 - 07 - 10 - 11 - 22 - 30
                   </td>
                   <td style="text-align: left;width:50px;">
                   </td>
                   <td style="text-align: right;width:50px;">
                   </td>
                   <td style="text-align: center;">
                    12 - 17 - 29 - 33 - 34 - 36
                   </td>
                   <td style="text-align: center;">
                    08/10/16
                   </td>
                  </tr>
                  <tr>
                   <td style="text-align: center;">
                    1614
                   </td>
                   <td style="text-align: center;">
                    09 - 18 - 23 - 31 - 32 - 36
                   </td>
                   <td style="text-align: left;width:50px;">
                   </td>
                   <td style="text-align: right;width:50px;">
                   </td>
                   <td style="text-align: center;">
                    01 - 16 - 26 - 29 - 31 - 32
                   </td>
                   <td style="text-align: center;">
                    05/10/16
                   </td>
                  </tr>
                  <tr>
                   <td style="text-align: center;">
                    1613

FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?